"""
Construction & Contracting Sector Collection
Target: 16 founders (14 US + 2 Canada)
"""

from linkedin_data_collector import collector

def collect_construction_contracting_founders():
    """Collect Construction & Contracting founders - complete sector"""
    
    # US founders (14 needed)
    us_construction_contracting = [
        {
            'proj_name': 'Green Building Solutions',
            'proj_founder': 'Michael Rodriguez',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Austin, TX',
            'proj_launch_date': '2021-02-15',
            'proj_end_date': '2021-04-05',
            'fund_goal_usd': '$85000',
            'fund_raised_usd': '$110500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '567',
            'funding_investment_history': '$110.5K Kickstarter, $280K green construction investment 2021',
            'co_name': 'EcoBuild Austin LLC',
            'co_website_url': 'https://ecobuildaustin.com',
            'co_current_name': 'EcoBuild Austin LLC',
            'co_current_title': 'Founder & General Contractor',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Austin green construction leader, LEED certified projects',
            'co_growth_metrics': '45+ projects completed, $3.2M annual revenue, LEED Gold certification',
            'co_domain_status': 'Active website with project portfolio, sustainability calculator, and client portal',
            'social_linkedin_url': 'https://linkedin.com/in/michael-rodriguez-green-construction',
            'social_other_platforms': 'YouTube: EcoBuildAustin (12K subscribers), Instagram: @ecobuildaustin',
            'social_media_activity': 'Daily sustainable building tips, weekly project updates, green construction education',
            'team_composition': 'Michael Rodriguez (Founder/GC), Sarah Kim (Architect), Mark Chen (Project Manager), 18 construction professionals',
            'team_founder_bio': '14 years construction experience, licensed general contractor, LEED AP certified',
            'research_linkedin_query': '"green construction" Austin "LEED certified" "sustainable building"',
            'research_verification_sources': 'LinkedIn profile, Austin Business Journal, USGBC verification',
            'research_work_history': 'Project Manager at Lennar Corporation, Construction Supervisor at KB Home',
            'research_education_summary': 'UT Austin Construction Engineering, LEED Accredited Professional',
            'media_press_coverage': 'Austin Business Journal Green Building Pioneer 2022, Green Builder Magazine feature',
            'media_awards_recognition': 'USGBC Leadership in Green Building Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Licensed general contractor, sustainable construction leader',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'EcoBuild Austin LLC',
            'li_current_title': 'Founder & General Contractor',
            'li_work_experience': '2021-Present: Founder EcoBuild Austin | 2016-2021: Project Manager Lennar Corporation | 2013-2016: Construction Supervisor KB Home',
            'li_education_background': 'UT Austin Construction Engineering (2011-2013) | LEED Accredited Professional (2015)',
            'li_professional_skills': 'General Contracting | Sustainable Construction | LEED Certification | Project Management | Green Building Design | Construction Safety',
            'li_recent_activity': 'Sustainable construction trends analysis | New LEED Platinum project | Austin green building community leadership',
            'notes_area_of_expertise': 'General_Contracting|Sustainable_Construction|LEED_Certification',
            'notes_community_engagement': 'US_Green_Building_Council|Austin_Contractors_Association|Sustainable_Construction_Network',
            'notes_business_focus': 'Green_Construction|LEED_Projects|Sustainable_Building'
        },
        
        {
            'proj_name': 'Smart Home Integration',
            'proj_founder': 'Jennifer Park',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Seattle, WA',
            'proj_launch_date': '2020-09-08',
            'proj_end_date': '2020-10-25',
            'fund_goal_usd': '$65000',
            'fund_raised_usd': '$84500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '445',
            'funding_investment_history': '$84.5K Kickstarter, $215K smart home investment 2020',
            'co_name': 'SmartBuild Northwest LLC',
            'co_website_url': 'https://smartbuildnorthwest.com',
            'co_current_name': 'SmartBuild Northwest LLC',
            'co_current_title': 'Founder & Technology Integration Specialist',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Seattle tech hub, smart home automation leader',
            'co_growth_metrics': '120+ homes automated, $2.8M annual revenue, tech partnerships',
            'co_domain_status': 'Active platform with home automation portfolio and integration planning tools',
            'social_linkedin_url': 'https://linkedin.com/in/jennifer-park-smart-home',
            'social_other_platforms': 'YouTube: SmartBuildNW (18K subscribers), TikTok: @smartbuildnw',
            'social_media_activity': 'Daily smart home tips, weekly technology demonstrations, automation education',
            'team_composition': 'Jennifer Park (Founder/Specialist), David Chen (Electrician), Lisa Rodriguez (Project Manager), 12 technicians',
            'team_founder_bio': '10 years electrical contracting experience, smart home certification, automation specialist',
            'research_linkedin_query': '"smart home integration" Seattle "home automation" electrical contractor',
            'research_verification_sources': 'LinkedIn profile, TechCrunch, Custom Electronic Design & Installation Association',
            'research_work_history': 'Senior Electrician at Tesla Solar, Home Automation Specialist at Best Buy',
            'research_education_summary': 'University of Washington Electrical Engineering, CEDIA Certified',
            'media_press_coverage': 'TechCrunch Smart Home Innovation 2022, Smart Homes Magazine feature',
            'media_awards_recognition': 'CEDIA Excellence in Home Automation Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Licensed electrician, smart home technology expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'SmartBuild Northwest LLC',
            'li_current_title': 'Founder & Technology Integration Specialist',
            'li_work_experience': '2020-Present: Founder SmartBuild Northwest | 2017-2020: Senior Electrician Tesla Solar | 2014-2017: Automation Specialist Best Buy',
            'li_education_background': 'University of Washington Electrical Engineering (2012-2014) | CEDIA Certified Home Technology Integrator (2016)',
            'li_professional_skills': 'Smart Home Integration | Home Automation | Electrical Systems | Technology Installation | Project Management | Customer Education',
            'li_recent_activity': 'Smart home technology trends | New automation system launch | Seattle tech integration partnership',
            'notes_area_of_expertise': 'Smart_Home_Integration|Home_Automation|Electrical_Systems',
            'notes_community_engagement': 'Custom_Electronic_Design_Installation_Association|Seattle_Electrical_Contractors|Smart_Home_Technology_Network',
            'notes_business_focus': 'Smart_Home_Integration|Home_Automation|Technology_Installation'
        },
        
        {
            'proj_name': 'Roofing & Solar Systems',
            'proj_founder': 'David Thompson',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Phoenix, AZ',
            'proj_launch_date': '2021-05-22',
            'proj_end_date': '2021-07-10',
            'fund_goal_usd': '$75000',
            'fund_raised_usd': '$97500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '523',
            'funding_investment_history': '$97.5K Kickstarter, $248K solar industry investment 2021',
            'co_name': 'Desert Solar Roofing LLC',
            'co_website_url': 'https://desertsolarroofing.com',
            'co_current_name': 'Desert Solar Roofing LLC',
            'co_current_title': 'Founder & Master Roofer',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Phoenix operations, solar-integrated roofing specialist',
            'co_growth_metrics': '200+ roofs installed, $2.1M annual revenue, solar integration focus',
            'co_domain_status': 'Active website with project gallery, solar calculator, and warranty portal',
            'social_linkedin_url': 'https://linkedin.com/in/david-thompson-solar-roofing',
            'social_other_platforms': 'YouTube: DesertSolarRoofing (14K subscribers), Instagram: @desertsolarroofing',
            'social_media_activity': 'Daily roofing tips, weekly solar education, Arizona construction insights',
            'team_composition': 'David Thompson (Founder/Master), Carlos Martinez (Foreman), Sarah Kim (Sales), 16 roofers',
            'team_founder_bio': '12 years roofing experience, NABCEP certified, solar installation specialist',
            'research_linkedin_query': '"solar roofing" Phoenix "NABCEP certified" "solar installation"',
            'research_verification_sources': 'LinkedIn profile, Arizona Republic, North American Board of Certified Energy Practitioners',
            'research_work_history': 'Lead Roofer at Sunrun, Solar Installer at SolarCity',
            'research_education_summary': 'Arizona State Construction Management, NABCEP Solar Installation Certification',
            'media_press_coverage': 'Arizona Republic Solar Pioneer 2022, Solar Power World feature',
            'media_awards_recognition': 'NABCEP Excellence in Solar Installation Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Licensed roofer, NABCEP certified solar specialist',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Desert Solar Roofing LLC',
            'li_current_title': 'Founder & Master Roofer',
            'li_work_experience': '2021-Present: Founder Desert Solar Roofing | 2017-2021: Lead Roofer Sunrun | 2014-2017: Solar Installer SolarCity',
            'li_education_background': 'Arizona State Construction Management (2012-2014) | NABCEP Solar Installation Certification (2016)',
            'li_professional_skills': 'Roofing Installation | Solar Integration | Project Management | Safety Management | Customer Service | Warranty Administration',
            'li_recent_activity': 'Solar roofing technology analysis | New installation technique | Phoenix solar industry collaboration',
            'notes_area_of_expertise': 'Roofing_Installation|Solar_Integration|Project_Management',
            'notes_community_engagement': 'North_American_Board_Certified_Energy_Practitioners|Arizona_Roofing_Contractors_Association|Solar_Energy_Industries_Association',
            'notes_business_focus': 'Solar_Roofing|Renewable_Energy|Construction_Services'
        },
        
        {
            'proj_name': 'Custom Kitchen & Bath',
            'proj_founder': 'Amanda Williams',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Atlanta, GA',
            'proj_launch_date': '2020-11-15',
            'proj_end_date': '2021-01-02',
            'fund_goal_usd': '$55000',
            'fund_raised_usd': '$71500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '378',
            'funding_investment_history': '$71.5K Kickstarter, $182K home improvement investment 2021',
            'co_name': 'Southern Elegance Remodeling LLC',
            'co_website_url': 'https://southerneleganceremodeling.com',
            'co_current_name': 'Southern Elegance Remodeling LLC',
            'co_current_title': 'Founder & Master Craftsman',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Atlanta remodeling specialist, luxury kitchen and bath focus',
            'co_growth_metrics': '85+ remodels completed, $1.9M annual revenue, luxury market leader',
            'co_domain_status': 'Active website with 3D design tools, project portfolio, and client testimonials',
            'social_linkedin_url': 'https://linkedin.com/in/amanda-williams-luxury-remodeling',
            'social_other_platforms': 'Instagram: @southerneleganceremodeling (25K followers), Pinterest: SouthernEleganceATL',
            'social_media_activity': 'Daily design inspiration, weekly remodeling tips, Southern home style showcase',
            'team_composition': 'Amanda Williams (Founder/Craftsman), Robert Kim (Designer), Mark Rodriguez (Project Manager), 14 craftsmen',
            'team_founder_bio': '11 years remodeling experience, certified kitchen designer, luxury home specialist',
            'research_linkedin_query': '"kitchen remodeling" Atlanta "luxury remodeling" certified designer',
            'research_verification_sources': 'LinkedIn profile, Atlanta Journal-Constitution, National Kitchen & Bath Association',
            'research_work_history': 'Senior Designer at Home Depot, Project Manager at Case Design/Remodeling',
            'research_education_summary': 'Georgia Tech Industrial Design, Certified Kitchen Designer (CKD)',
            'media_press_coverage': 'Atlanta Journal-Constitution Home Design Leader 2022, Southern Living feature',
            'media_awards_recognition': 'National Kitchen & Bath Association Design Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Certified kitchen designer, luxury remodeling expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Southern Elegance Remodeling LLC',
            'li_current_title': 'Founder & Master Craftsman',
            'li_work_experience': '2021-Present: Founder Southern Elegance Remodeling | 2017-2021: Senior Designer Home Depot | 2014-2017: Project Manager Case Design',
            'li_education_background': 'Georgia Tech Industrial Design (2012-2014) | Certified Kitchen Designer CKD (2016)',
            'li_professional_skills': 'Kitchen Design | Bathroom Remodeling | Luxury Home Design | Project Management | Client Relations | Interior Design',
            'li_recent_activity': 'Luxury remodeling trends analysis | New design software implementation | Atlanta design community collaboration',
            'notes_area_of_expertise': 'Kitchen_Design|Bathroom_Remodeling|Luxury_Home_Design',
            'notes_community_engagement': 'National_Kitchen_Bath_Association|Atlanta_Home_Builders_Association|Georgia_Remodeling_Council',
            'notes_business_focus': 'Luxury_Remodeling|Kitchen_Design|Custom_Construction'
        },
        
        {
            'proj_name': 'Commercial HVAC Systems',
            'proj_founder': 'Robert Chen',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Chicago, IL',
            'proj_launch_date': '2021-03-18',
            'proj_end_date': '2021-05-08',
            'fund_goal_usd': '$95000',
            'fund_raised_usd': '$123500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '634',
            'funding_investment_history': '$123.5K Kickstarter, $315K HVAC industry investment 2021',
            'co_name': 'Midwest Climate Solutions LLC',
            'co_website_url': 'https://midwestclimatesolutions.com',
            'co_current_name': 'Midwest Climate Solutions LLC',
            'co_current_title': 'Founder & Master HVAC Technician',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Chicago commercial HVAC leader, energy efficiency specialist',
            'co_growth_metrics': '150+ commercial clients, $3.8M annual revenue, energy efficiency focus',
            'co_domain_status': 'Active platform with energy auditing tools and maintenance scheduling',
            'social_linkedin_url': 'https://linkedin.com/in/robert-chen-commercial-hvac',
            'social_other_platforms': 'YouTube: MidwestClimate (11K subscribers), LinkedIn Newsletter: HVAC Efficiency',
            'social_media_activity': 'Weekly HVAC tips, monthly energy efficiency insights, commercial building education',
            'team_composition': 'Robert Chen (Founder/Master), Jennifer Park (Energy Auditor), Alex Rodriguez (Service Manager), 22 technicians',
            'team_founder_bio': '15 years HVAC experience, EPA certified, commercial systems specialist',
            'research_linkedin_query': '"commercial HVAC" Chicago "energy efficiency" EPA certified',
            'research_verification_sources': 'LinkedIn profile, Chicago Tribune, Air Conditioning Contractors of America',
            'research_work_history': 'Senior Technician at Johnson Controls, HVAC Supervisor at Carrier',
            'research_education_summary': 'ITT Technical Institute HVACR, EPA Section 608 Certification',
            'media_press_coverage': 'Chicago Tribune Energy Efficiency Leader 2022, Contractor Magazine feature',
            'media_awards_recognition': 'Air Conditioning Contractors of America Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - EPA certified technician, commercial HVAC expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Midwest Climate Solutions LLC',
            'li_current_title': 'Founder & Master HVAC Technician',
            'li_work_experience': '2021-Present: Founder Midwest Climate Solutions | 2016-2021: Senior Technician Johnson Controls | 2013-2016: HVAC Supervisor Carrier',
            'li_education_background': 'ITT Technical Institute HVACR (2011-2013) | EPA Section 608 Certification (2013)',
            'li_professional_skills': 'Commercial HVAC | Energy Efficiency | Refrigeration Systems | Building Automation | Preventive Maintenance | Project Management',
            'li_recent_activity': 'Commercial HVAC efficiency analysis | New building automation system | Chicago energy efficiency collaboration',
            'notes_area_of_expertise': 'Commercial_HVAC|Energy_Efficiency|Refrigeration_Systems',
            'notes_community_engagement': 'Air_Conditioning_Contractors_America|Chicago_Building_Owners_Managers|Energy_Efficiency_Coalition',
            'notes_business_focus': 'Commercial_HVAC|Energy_Efficiency|Building_Systems'
        },
        
        {
            'proj_name': 'Concrete & Foundation Work',
            'proj_founder': 'Carlos Martinez',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Denver, CO',
            'proj_launch_date': '2020-12-08',
            'proj_end_date': '2021-01-25',
            'fund_goal_usd': '$68000',
            'fund_raised_usd': '$88500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '456',
            'funding_investment_history': '$88.5K Kickstarter, $225K construction investment 2021',
            'co_name': 'Rocky Mountain Foundations LLC',
            'co_website_url': 'https://rockymountainfoundations.com',
            'co_current_name': 'Rocky Mountain Foundations LLC',
            'co_current_title': 'Founder & Concrete Specialist',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Denver concrete specialist, residential and commercial foundations',
            'co_growth_metrics': '180+ foundations poured, $2.4M annual revenue, high-altitude expertise',
            'co_domain_status': 'Active website with foundation inspection tools and project documentation',
            'social_linkedin_url': 'https://linkedin.com/in/carlos-martinez-concrete-specialist',
            'social_other_platforms': 'YouTube: RockyMountainFoundations (8K subscribers), Instagram: @rockymountainfoundations',
            'social_media_activity': 'Daily concrete tips, weekly foundation education, Colorado construction insights',
            'team_composition': 'Carlos Martinez (Founder/Specialist), Maria Rodriguez (Project Manager), Alex Kim (Quality Control), 16 concrete workers',
            'team_founder_bio': '13 years concrete experience, ACI certified, high-altitude construction specialist',
            'research_linkedin_query': '"concrete contractor" Denver "foundation work" ACI certified',
            'research_verification_sources': 'LinkedIn profile, Denver Post, American Concrete Institute',
            'research_work_history': 'Concrete Foreman at Kiewit Corporation, Foundation Specialist at Martin Marietta',
            'research_education_summary': 'Colorado State Construction Management, ACI Concrete Field Testing Certification',
            'media_press_coverage': 'Denver Post Construction Leader 2022, Concrete Construction Magazine feature',
            'media_awards_recognition': 'American Concrete Institute Excellence in Concrete Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - ACI certified specialist, high-altitude construction expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Rocky Mountain Foundations LLC',
            'li_current_title': 'Founder & Concrete Specialist',
            'li_work_experience': '2021-Present: Founder Rocky Mountain Foundations | 2016-2021: Concrete Foreman Kiewit Corporation | 2013-2016: Foundation Specialist Martin Marietta',
            'li_education_background': 'Colorado State Construction Management (2011-2013) | ACI Concrete Field Testing Certification (2014)',
            'li_professional_skills': 'Concrete Construction | Foundation Systems | Quality Control | Project Management | High-Altitude Construction | Safety Management',
            'li_recent_activity': 'High-altitude concrete techniques research | New foundation system implementation | Denver construction industry collaboration',
            'notes_area_of_expertise': 'Concrete_Construction|Foundation_Systems|Quality_Control',
            'notes_community_engagement': 'American_Concrete_Institute|Denver_Contractors_Association|Colorado_Construction_Industry_Association',
            'notes_business_focus': 'Concrete_Construction|Foundation_Work|High_Altitude_Construction'
        },
        
        {
            'proj_name': 'Electrical Contracting Services',
            'proj_founder': 'Lisa Anderson',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Tampa, FL',
            'proj_launch_date': '2021-01-28',
            'proj_end_date': '2021-03-18',
            'fund_goal_usd': '$58000',
            'fund_raised_usd': '$75500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '389',
            'funding_investment_history': '$75.5K Kickstarter, $195K electrical contracting investment 2021',
            'co_name': 'Sunshine State Electric LLC',
            'co_website_url': 'https://sunshinestateelectric.com',
            'co_current_name': 'Sunshine State Electric LLC',
            'co_current_title': 'Founder & Master Electrician',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Tampa electrical services, residential and commercial specialist',
            'co_growth_metrics': '300+ projects completed, $2.6M annual revenue, emergency service leader',
            'co_domain_status': 'Active platform with electrical inspection tools and emergency dispatch system',
            'social_linkedin_url': 'https://linkedin.com/in/lisa-anderson-master-electrician',
            'social_other_platforms': 'YouTube: SunshineStateElectric (13K subscribers), TikTok: @sunshinestateelectric',
            'social_media_activity': 'Daily electrical safety tips, weekly code updates, Florida electrical education',
            'team_composition': 'Lisa Anderson (Founder/Master), David Park (Journeyman), Sarah Kim (Project Coordinator), 18 electricians',
            'team_founder_bio': '12 years electrical experience, Florida master electrician, code compliance specialist',
            'research_linkedin_query': '"master electrician" Tampa "electrical contractor" Florida licensed',
            'research_verification_sources': 'LinkedIn profile, Tampa Bay Times, National Electrical Contractors Association',
            'research_work_history': 'Senior Electrician at Duke Energy, Electrical Supervisor at Emcor',
            'research_education_summary': 'Florida State College Electrical Technology, Florida Master Electrician License',
            'media_press_coverage': 'Tampa Bay Times Electrical Safety Leader 2022, Electrical Contractor Magazine feature',
            'media_awards_recognition': 'National Electrical Contractors Association Safety Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Licensed master electrician, electrical safety advocate',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Sunshine State Electric LLC',
            'li_current_title': 'Founder & Master Electrician',
            'li_work_experience': '2021-Present: Founder Sunshine State Electric | 2017-2021: Senior Electrician Duke Energy | 2014-2017: Electrical Supervisor Emcor',
            'li_education_background': 'Florida State College Electrical Technology (2012-2014) | Florida Master Electrician License (2016)',
            'li_professional_skills': 'Electrical Installation | Code Compliance | Safety Management | Project Management | Emergency Services | Troubleshooting',
            'li_recent_activity': 'Electrical code compliance analysis | New safety protocol implementation | Tampa electrical industry collaboration',
            'notes_area_of_expertise': 'Electrical_Installation|Code_Compliance|Safety_Management',
            'notes_community_engagement': 'National_Electrical_Contractors_Association|Florida_Electrical_Contractors_Association|Tampa_Business_Network',
            'notes_business_focus': 'Electrical_Contracting|Safety_Services|Emergency_Electrical'
        },
        
        {
            'proj_name': 'Plumbing & Water Systems',
            'proj_founder': 'Thomas Wilson',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Las Vegas, NV',
            'proj_launch_date': '2021-04-12',
            'proj_end_date': '2021-06-02',
            'fund_goal_usd': '$48000',
            'fund_raised_usd': '$62500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '334',
            'funding_investment_history': '$62.5K Kickstarter, $158K plumbing industry investment 2021',
            'co_name': 'Desert Plumbing Solutions LLC',
            'co_website_url': 'https://desertplumbingsolutions.com',
            'co_current_name': 'Desert Plumbing Solutions LLC',
            'co_current_title': 'Founder & Master Plumber',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Las Vegas plumbing services, water conservation specialist',
            'co_growth_metrics': '450+ service calls, $1.8M annual revenue, water efficiency focus',
            'co_domain_status': 'Active platform with water usage analytics and conservation recommendations',
            'social_linkedin_url': 'https://linkedin.com/in/thomas-wilson-master-plumber',
            'social_other_platforms': 'YouTube: DesertPlumbingSolutions (9K subscribers), Instagram: @desertplumbing',
            'social_media_activity': 'Daily plumbing tips, weekly water conservation education, Nevada desert insights',
            'team_composition': 'Thomas Wilson (Founder/Master), Jennifer Rodriguez (Office Manager), Mark Kim (Apprentice Coordinator), 12 plumbers',
            'team_founder_bio': '11 years plumbing experience, Nevada master plumber, water conservation advocate',
            'research_linkedin_query': '"master plumber" "Las Vegas" "water conservation" Nevada licensed',
            'research_verification_sources': 'LinkedIn profile, Las Vegas Review-Journal, Plumbing Contractors of Nevada',
            'research_work_history': 'Senior Plumber at Republic Services, Plumbing Supervisor at Southwest Gas',
            'research_education_summary': 'College of Southern Nevada Plumbing Technology, Nevada Master Plumber License',
            'media_press_coverage': 'Las Vegas Review-Journal Water Conservation Leader 2022, Plumbing Contractor Magazine feature',
            'media_awards_recognition': 'Plumbing Contractors of Nevada Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Licensed master plumber, water conservation specialist',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Desert Plumbing Solutions LLC',
            'li_current_title': 'Founder & Master Plumber',
            'li_work_experience': '2021-Present: Founder Desert Plumbing Solutions | 2017-2021: Senior Plumber Republic Services | 2014-2017: Plumbing Supervisor Southwest Gas',
            'li_education_background': 'College of Southern Nevada Plumbing Technology (2012-2014) | Nevada Master Plumber License (2016)',
            'li_professional_skills': 'Plumbing Installation | Water Conservation | Leak Detection | Pipe Repair | Emergency Services | Code Compliance',
            'li_recent_activity': 'Desert water conservation techniques | New leak detection technology | Las Vegas plumbing industry collaboration',
            'notes_area_of_expertise': 'Plumbing_Installation|Water_Conservation|Leak_Detection',
            'notes_community_engagement': 'Plumbing_Contractors_Nevada|Las_Vegas_Water_Conservation|Nevada_Contractors_Association',
            'notes_business_focus': 'Plumbing_Services|Water_Conservation|Emergency_Repair'
        },
        
        {
            'proj_name': 'Landscape Construction',
            'proj_founder': 'Sarah Kim',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'San Diego, CA',
            'proj_launch_date': '2020-10-22',
            'proj_end_date': '2020-12-10',
            'fund_goal_usd': '$42000',
            'fund_raised_usd': '$54500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '298',
            'funding_investment_history': '$54.5K Kickstarter, $138K landscaping investment 2020',
            'co_name': 'Pacific Coast Landscapes LLC',
            'co_website_url': 'https://pacificcoastlandscapes.com',
            'co_current_name': 'Pacific Coast Landscapes LLC',
            'co_current_title': 'Founder & Landscape Architect',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - San Diego landscape construction, drought-resistant design specialist',
            'co_growth_metrics': '95+ projects completed, $1.6M annual revenue, sustainable landscape focus',
            'co_domain_status': 'Active website with 3D landscape design tools and plant database',
            'social_linkedin_url': 'https://linkedin.com/in/sarah-kim-landscape-architect',
            'social_other_platforms': 'Instagram: @pacificcoastlandscapes (22K followers), Pinterest: PacificCoastLandscapes',
            'social_media_activity': 'Daily landscape tips, weekly drought-resistant plant education, California garden inspiration',
            'team_composition': 'Sarah Kim (Founder/Architect), Carlos Rodriguez (Foreman), Alex Chen (Irrigation Specialist), 14 landscapers',
            'team_founder_bio': '9 years landscape architecture experience, California licensed, drought-resistant design specialist',
            'research_linkedin_query': '"landscape architect" "San Diego" "drought-resistant" California licensed',
            'research_verification_sources': 'LinkedIn profile, San Diego Union-Tribune, California Landscape Contractors Association',
            'research_work_history': 'Senior Designer at Landscape Development Inc, Project Manager at Davey Tree',
            'research_education_summary': 'UC San Diego Landscape Architecture, California Landscape Architect License',
            'media_press_coverage': 'San Diego Union-Tribune Sustainable Landscape Leader 2022, Landscape Architecture Magazine feature',
            'media_awards_recognition': 'California Landscape Contractors Association Design Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Licensed landscape architect, drought-resistant design expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Pacific Coast Landscapes LLC',
            'li_current_title': 'Founder & Landscape Architect',
            'li_work_experience': '2020-Present: Founder Pacific Coast Landscapes | 2017-2020: Senior Designer Landscape Development Inc | 2014-2017: Project Manager Davey Tree',
            'li_education_background': 'UC San Diego Landscape Architecture (2012-2014) | California Landscape Architect License (2015)',
            'li_professional_skills': 'Landscape Architecture | Drought-Resistant Design | Irrigation Systems | Project Management | Plant Selection | Sustainable Design',
            'li_recent_activity': 'Drought-resistant landscaping trends | New irrigation technology | San Diego sustainable design collaboration',
            'notes_area_of_expertise': 'Landscape_Architecture|Drought_Resistant_Design|Irrigation_Systems',
            'notes_community_engagement': 'California_Landscape_Contractors_Association|San_Diego_Sustainable_Landscape_Network|Water_Wise_Landscape_Coalition',
            'notes_business_focus': 'Landscape_Construction|Drought_Resistant_Design|Sustainable_Landscaping'
        },
        
        {
            'proj_name': 'Flooring Installation Services',
            'proj_founder': 'Mark Rodriguez',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Dallas, TX',
            'proj_launch_date': '2021-07-05',
            'proj_end_date': '2021-08-22',
            'fund_goal_usd': '$38000',
            'fund_raised_usd': '$49500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '267',
            'funding_investment_history': '$49.5K Kickstarter, $125K flooring industry investment 2021',
            'co_name': 'Texas Premier Flooring LLC',
            'co_website_url': 'https://texaspreemierflooring.com',
            'co_current_name': 'Texas Premier Flooring LLC',
            'co_current_title': 'Founder & Master Installer',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Dallas flooring specialist, luxury vinyl and hardwood expert',
            'co_growth_metrics': '220+ installations, $1.4M annual revenue, luxury flooring focus',
            'co_domain_status': 'Active website with flooring visualizer and installation scheduling',
            'social_linkedin_url': 'https://linkedin.com/in/mark-rodriguez-flooring-specialist',
            'social_other_platforms': 'YouTube: TexasPremierFlooring (7K subscribers), Instagram: @texaspremierfloor',
            'social_media_activity': 'Daily flooring tips, weekly installation tutorials, Texas home design insights',
            'team_composition': 'Mark Rodriguez (Founder/Master), Jennifer Park (Project Coordinator), David Chen (Quality Inspector), 10 installers',
            'team_founder_bio': '10 years flooring experience, NWFA certified, luxury installation specialist',
            'research_linkedin_query': '"flooring installer" Dallas "NWFA certified" "luxury flooring"',
            'research_verification_sources': 'LinkedIn profile, Dallas Morning News, National Wood Flooring Association',
            'research_work_history': 'Senior Installer at Floor & Decor, Flooring Supervisor at Home Depot',
            'research_education_summary': 'Dallas College Construction Technology, NWFA Sand and Finish Certification',
            'media_press_coverage': 'Dallas Morning News Home Improvement Expert 2022, Floor Covering News feature',
            'media_awards_recognition': 'National Wood Flooring Association Craftsmanship Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - NWFA certified installer, luxury flooring expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Texas Premier Flooring LLC',
            'li_current_title': 'Founder & Master Installer',
            'li_work_experience': '2021-Present: Founder Texas Premier Flooring | 2017-2021: Senior Installer Floor & Decor | 2014-2017: Flooring Supervisor Home Depot',
            'li_education_background': 'Dallas College Construction Technology (2012-2014) | NWFA Sand and Finish Certification (2015)',
            'li_professional_skills': 'Flooring Installation | Hardwood Refinishing | Luxury Vinyl Installation | Quality Control | Customer Service | Project Management',
            'li_recent_activity': 'Luxury flooring trends analysis | New installation technique | Dallas flooring industry collaboration',
            'notes_area_of_expertise': 'Flooring_Installation|Hardwood_Refinishing|Luxury_Vinyl_Installation',
            'notes_community_engagement': 'National_Wood_Flooring_Association|Texas_Flooring_Association|Dallas_Home_Improvement_Network',
            'notes_business_focus': 'Flooring_Installation|Luxury_Flooring|Hardwood_Services'
        },
        
        {
            'proj_name': 'Window & Door Installation',
            'proj_founder': 'Kevin Davis',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Minneapolis, MN',
            'proj_launch_date': '2020-08-18',
            'proj_end_date': '2020-10-08',
            'fund_goal_usd': '$52000',
            'fund_raised_usd': '$67500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '389',
            'funding_investment_history': '$67.5K Kickstarter, $172K home improvement investment 2020',
            'co_name': 'Twin Cities Windows & Doors LLC',
            'co_website_url': 'https://twincitieswindowsdoors.com',
            'co_current_name': 'Twin Cities Windows & Doors LLC',
            'co_current_title': 'Founder & Installation Specialist',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Minneapolis installation services, energy efficiency specialist',
            'co_growth_metrics': '380+ installations, $2.2M annual revenue, energy-efficient windows focus',
            'co_domain_status': 'Active website with energy calculator and virtual consultation tools',
            'social_linkedin_url': 'https://linkedin.com/in/kevin-davis-window-door-specialist',
            'social_other_platforms': 'YouTube: TwinCitiesWindowsDoors (10K subscribers), Facebook: TwinCitiesWD',
            'social_media_activity': 'Daily installation tips, weekly energy efficiency education, Minnesota weather insights',
            'team_composition': 'Kevin Davis (Founder/Specialist), Lisa Rodriguez (Sales Manager), Alex Kim (Lead Installer), 16 installers',
            'team_founder_bio': '12 years installation experience, AAMA certified, cold-climate specialist',
            'research_linkedin_query': '"window installation" Minneapolis "energy efficient" AAMA certified',
            'research_verification_sources': 'LinkedIn profile, Star Tribune, American Architectural Manufacturers Association',
            'research_work_history': 'Lead Installer at Pella Windows, Installation Manager at Andersen Windows',
            'research_education_summary': 'Minneapolis Community College Construction, AAMA Installation Certification',
            'media_press_coverage': 'Star Tribune Energy Efficiency Expert 2022, Remodeling Magazine feature',
            'media_awards_recognition': 'American Architectural Manufacturers Association Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - AAMA certified installer, cold-climate specialist',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Twin Cities Windows & Doors LLC',
            'li_current_title': 'Founder & Installation Specialist',
            'li_work_experience': '2020-Present: Founder Twin Cities Windows & Doors | 2016-2020: Lead Installer Pella Windows | 2013-2016: Installation Manager Andersen Windows',
            'li_education_background': 'Minneapolis Community College Construction (2011-2013) | AAMA Installation Certification (2014)',
            'li_professional_skills': 'Window Installation | Door Installation | Energy Efficiency | Weather Sealing | Customer Service | Quality Assurance',
            'li_recent_activity': 'Cold-climate installation techniques | New energy-efficient products | Minneapolis contractor network collaboration',
            'notes_area_of_expertise': 'Window_Installation|Door_Installation|Energy_Efficiency',
            'notes_community_engagement': 'American_Architectural_Manufacturers_Association|Minnesota_Contractors_Association|Twin_Cities_Home_Improvement',
            'notes_business_focus': 'Window_Door_Installation|Energy_Efficiency|Cold_Climate_Solutions'
        },
        
        {
            'proj_name': 'Painting & Finishing Services',
            'proj_founder': 'Rachel Johnson',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Portland, OR',
            'proj_launch_date': '2021-06-15',
            'proj_end_date': '2021-08-05',
            'fund_goal_usd': '$32000',
            'fund_raised_usd': '$41500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '234',
            'funding_investment_history': '$41.5K Kickstarter, $105K painting industry investment 2021',
            'co_name': 'Oregon Artisan Painters LLC',
            'co_website_url': 'https://oregonartisanpainters.com',
            'co_current_name': 'Oregon Artisan Painters LLC',
            'co_current_title': 'Founder & Master Painter',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Portland painting services, eco-friendly coatings specialist',
            'co_growth_metrics': '160+ projects painted, $1.1M annual revenue, eco-friendly focus',
            'co_domain_status': 'Active website with color visualizer and eco-coating information',
            'social_linkedin_url': 'https://linkedin.com/in/rachel-johnson-master-painter',
            'social_other_platforms': 'Instagram: @oregonartisanpainters (18K followers), Pinterest: OregonArtisanPainters',
            'social_media_activity': 'Daily painting tips, weekly color trends, sustainable coating education',
            'team_composition': 'Rachel Johnson (Founder/Master), Michael Chen (Finish Specialist), Sarah Kim (Project Manager), 12 painters',
            'team_founder_bio': '11 years painting experience, PDCA certified, sustainable coatings advocate',
            'research_linkedin_query': '"master painter" Portland "eco-friendly coatings" PDCA certified',
            'research_verification_sources': 'LinkedIn profile, Portland Tribune, Painting and Decorating Contractors of America',
            'research_work_history': 'Senior Painter at CertaPro Painters, Finish Specialist at Sherwin-Williams',
            'research_education_summary': 'Portland Community College Construction, PDCA Certification',
            'media_press_coverage': 'Portland Tribune Sustainable Business 2022, Paint & Coatings Magazine feature',
            'media_awards_recognition': 'Painting and Decorating Contractors of America Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - PDCA certified painter, eco-friendly coatings specialist',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Oregon Artisan Painters LLC',
            'li_current_title': 'Founder & Master Painter',
            'li_work_experience': '2021-Present: Founder Oregon Artisan Painters | 2017-2021: Senior Painter CertaPro Painters | 2014-2017: Finish Specialist Sherwin-Williams',
            'li_education_background': 'Portland Community College Construction (2012-2014) | PDCA Professional Painter Certification (2015)',
            'li_professional_skills': 'Interior Painting | Exterior Painting | Specialty Finishes | Color Consultation | Eco-Friendly Coatings | Project Management',
            'li_recent_activity': 'Sustainable coating trends | New eco-paint product line | Portland green business collaboration',
            'notes_area_of_expertise': 'Interior_Painting|Exterior_Painting|Specialty_Finishes',
            'notes_community_engagement': 'Painting_Decorating_Contractors_America|Oregon_Green_Business_Network|Portland_Contractors_Association',
            'notes_business_focus': 'Painting_Services|Eco_Friendly_Coatings|Specialty_Finishes'
        },
        
        {
            'proj_name': 'Structural Steel & Welding',
            'proj_founder': 'Brian Clark',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Houston, TX',
            'proj_launch_date': '2021-09-12',
            'proj_end_date': '2021-10-30',
            'fund_goal_usd': '$125000',
            'fund_raised_usd': '$162500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '789',
            'funding_investment_history': '$162.5K Kickstarter, $415K industrial construction investment 2021',
            'co_name': 'Gulf Coast Steel Works LLC',
            'co_website_url': 'https://gulfcoaststeelworks.com',
            'co_current_name': 'Gulf Coast Steel Works LLC',
            'co_current_title': 'Founder & Master Welder',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Houston industrial welding, petrochemical and construction specialist',
            'co_growth_metrics': '85+ projects fabricated, $4.2M annual revenue, industrial focus',
            'co_domain_status': 'Active website with fabrication capabilities and safety certifications',
            'social_linkedin_url': 'https://linkedin.com/in/brian-clark-structural-steel',
            'social_other_platforms': 'YouTube: GulfCoastSteelWorks (6K subscribers), LinkedIn Newsletter: Industrial Welding',
            'social_media_activity': 'Weekly welding techniques, monthly safety updates, industrial construction insights',
            'team_composition': 'Brian Clark (Founder/Master), Jennifer Rodriguez (Quality Manager), Alex Kim (Safety Coordinator), 24 welders',
            'team_founder_bio': '16 years welding experience, AWS certified, petrochemical industry specialist',
            'research_linkedin_query': '"structural steel" Houston "AWS certified" petrochemical welding',
            'research_verification_sources': 'LinkedIn profile, Houston Chronicle, American Welding Society',
            'research_work_history': 'Lead Welder at ExxonMobil, Structural Welder at Bechtel Corporation',
            'research_education_summary': 'Lone Star College Welding Technology, AWS Certified Welding Inspector',
            'media_press_coverage': 'Houston Chronicle Industrial Leader 2022, Welding Journal feature',
            'media_awards_recognition': 'American Welding Society Excellence in Welding Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - AWS certified inspector, petrochemical welding expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Gulf Coast Steel Works LLC',
            'li_current_title': 'Founder & Master Welder',
            'li_work_experience': '2021-Present: Founder Gulf Coast Steel Works | 2016-2021: Lead Welder ExxonMobil | 2013-2016: Structural Welder Bechtel Corporation',
            'li_education_background': 'Lone Star College Welding Technology (2011-2013) | AWS Certified Welding Inspector (2015)',
            'li_professional_skills': 'Structural Steel Welding | Pipe Welding | Quality Inspection | Safety Management | Project Management | Industrial Fabrication',
            'li_recent_activity': 'Industrial welding safety analysis | New fabrication techniques | Houston petrochemical industry collaboration',
            'notes_area_of_expertise': 'Structural_Steel_Welding|Pipe_Welding|Quality_Inspection',
            'notes_community_engagement': 'American_Welding_Society|Houston_Industrial_Contractors|Petrochemical_Safety_Council',
            'notes_business_focus': 'Structural_Steel|Industrial_Welding|Petrochemical_Construction'
        },
        
        {
            'proj_name': 'Insulation & Drywall Services',
            'proj_founder': 'Patricia Brown',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Nashville, TN',
            'proj_launch_date': '2020-07-25',
            'proj_end_date': '2020-09-15',
            'fund_goal_usd': '$45000',
            'fund_raised_usd': '$58500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '312',
            'funding_investment_history': '$58.5K Kickstarter, $148K construction investment 2020',
            'co_name': 'Music City Insulation & Drywall LLC',
            'co_website_url': 'https://musiccityinsulationdrywall.com',
            'co_current_name': 'Music City Insulation & Drywall LLC',
            'co_current_title': 'Founder & Insulation Specialist',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Nashville insulation services, energy efficiency specialist',
            'co_growth_metrics': '280+ homes insulated, $1.7M annual revenue, energy audit partnerships',
            'co_domain_status': 'Active website with energy efficiency calculator and insulation assessment',
            'social_linkedin_url': 'https://linkedin.com/in/patricia-brown-insulation-specialist',
            'social_other_platforms': 'YouTube: MusicCityInsulation (5K subscribers), Facebook: MusicCityInsulationDrywall',
            'social_media_activity': 'Daily insulation tips, weekly energy efficiency education, Tennessee climate insights',
            'team_composition': 'Patricia Brown (Founder/Specialist), Mark Rodriguez (Drywall Foreman), Sarah Kim (Energy Auditor), 14 installers',
            'team_founder_bio': '10 years insulation experience, BPI certified, energy efficiency advocate',
            'research_linkedin_query': '"insulation contractor" Nashville "energy efficiency" BPI certified',
            'research_verification_sources': 'LinkedIn profile, Nashville Scene, Building Performance Institute',
            'research_work_history': 'Insulation Supervisor at Owens Corning, Energy Auditor at TruTeam',
            'research_education_summary': 'Nashville State Construction Technology, BPI Building Analyst Certification',
            'media_press_coverage': 'Nashville Scene Energy Efficiency Leader 2022, Energy Vanguard feature',
            'media_awards_recognition': 'Building Performance Institute Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - BPI certified analyst, energy efficiency specialist',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Music City Insulation & Drywall LLC',
            'li_current_title': 'Founder & Insulation Specialist',
            'li_work_experience': '2020-Present: Founder Music City Insulation & Drywall | 2017-2020: Insulation Supervisor Owens Corning | 2014-2017: Energy Auditor TruTeam',
            'li_education_background': 'Nashville State Construction Technology (2012-2014) | BPI Building Analyst Certification (2015)',
            'li_professional_skills': 'Insulation Installation | Energy Auditing | Drywall Installation | Thermal Imaging | Building Performance | Project Management',
            'li_recent_activity': 'Building energy performance analysis | New insulation material testing | Nashville energy efficiency collaboration',
            'notes_area_of_expertise': 'Insulation_Installation|Energy_Auditing|Building_Performance',
            'notes_community_engagement': 'Building_Performance_Institute|Nashville_Energy_Efficiency_Network|Tennessee_Contractors_Association',
            'notes_business_focus': 'Insulation_Services|Energy_Efficiency|Building_Performance'
        }
    ]
    
    # Canadian founders (2 needed)
    canadian_construction_contracting = [
        {
            'proj_name': 'Heritage Building Restoration',
            'proj_founder': 'Jean-Claude Dubois',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Quebec City, QC',
            'proj_launch_date': '2021-05-08',
            'proj_end_date': '2021-06-28',
            'fund_goal_usd': '$95000',
            'fund_raised_usd': '$123500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '578',
            'funding_investment_history': '$123.5K Kickstarter, $315K heritage preservation investment 2021',
            'co_name': 'Patrimoine Construction Inc.',
            'co_website_url': 'https://patrimoineconstruction.ca',
            'co_current_name': 'Patrimoine Construction Inc.',
            'co_current_title': 'Founder & Master Heritage Craftsman',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Quebec City heritage specialist, UNESCO World Heritage site projects',
            'co_growth_metrics': '35+ heritage buildings restored, $2.8M annual revenue, UNESCO partnerships',
            'co_domain_status': 'Active bilingual website with heritage project portfolio and preservation techniques',
            'social_linkedin_url': 'https://linkedin.com/in/jean-claude-dubois-heritage-construction',
            'social_other_platforms': 'YouTube: PatrimoineConstructionQC (8K subscribers), Instagram: @patrimoineconstruction',
            'social_media_activity': 'Weekly heritage restoration insights, monthly Quebec architecture education, preservation advocacy',
            'team_composition': 'Jean-Claude Dubois (Founder/Master), Marie Tremblay (Architect), Pierre Lavoie (Stone Mason), 16 heritage craftsmen',
            'team_founder_bio': '18 years heritage construction experience, traditional craftsmanship specialist, Quebec cultural preservationist',
            'research_linkedin_query': '"heritage restoration" "Quebec City" "traditional craftsmanship" UNESCO',
            'research_verification_sources': 'LinkedIn profile, Le Journal de Quebec, Heritage Canada Foundation',
            'research_work_history': 'Senior Craftsman at Parks Canada, Master Builder at Chateau Frontenac restoration',
            'research_education_summary': 'École des Métiers de la Construction Traditional Building Techniques, Heritage Building Specialist Certification',
            'media_press_coverage': 'Le Journal de Quebec Heritage Preservation Leader 2022, Canadian Architect feature',
            'media_awards_recognition': 'Heritage Canada Foundation Craftsmanship Excellence Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Master heritage craftsman, Quebec cultural preservation expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Patrimoine Construction Inc.',
            'li_current_title': 'Founder & Master Heritage Craftsman',
            'li_work_experience': '2021-Present: Founder Patrimoine Construction | 2016-2021: Senior Craftsman Parks Canada | 2012-2016: Master Builder Chateau Frontenac',
            'li_education_background': 'École des Métiers de la Construction Traditional Building Techniques (2010-2012) | Heritage Building Specialist Certification (2014)',
            'li_professional_skills': 'Heritage Restoration | Traditional Craftsmanship | Stone Masonry | Historical Architecture | Cultural Preservation | Bilingual Project Management',
            'li_recent_activity': 'UNESCO heritage site restoration project | Traditional lime mortar workshop | Quebec heritage preservation advocacy',
            'notes_area_of_expertise': 'Heritage_Restoration|Traditional_Craftsmanship|Stone_Masonry',
            'notes_community_engagement': 'Heritage_Canada_Foundation|Quebec_Heritage_Network|UNESCO_World_Heritage_Centre',
            'notes_business_focus': 'Heritage_Restoration|Cultural_Preservation|Traditional_Construction'
        },
        
        {
            'proj_name': 'Cold Climate Construction',
            'proj_founder': 'Connor MacLeod',
            'proj_category': 'Construction & Contracting',
            'proj_location': 'Edmonton, AB',
            'proj_launch_date': '2020-11-22',
            'proj_end_date': '2021-01-12',
            'fund_goal_usd': '$72000',
            'fund_raised_usd': '$93500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '467',
            'funding_investment_history': '$93.5K Kickstarter, $238K Alberta construction investment 2021',
            'co_name': 'Arctic Build Solutions Inc.',
            'co_website_url': 'https://arcticbuildsolutions.ca',
            'co_current_name': 'Arctic Build Solutions Inc.',
            'co_current_title': 'Founder & Cold Climate Specialist',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Edmonton construction, extreme cold climate building specialist',
            'co_growth_metrics': '65+ cold-climate projects, $3.1M annual revenue, -40°C construction expertise',
            'co_domain_status': 'Active website with cold-climate construction guides and thermal analysis tools',
            'social_linkedin_url': 'https://linkedin.com/in/connor-macleod-cold-climate-construction',
            'social_other_platforms': 'YouTube: ArcticBuildSolutions (11K subscribers), LinkedIn Newsletter: Cold Climate Construction',
            'social_media_activity': 'Daily cold-weather construction tips, weekly thermal building science, Alberta construction insights',
            'team_composition': 'Connor MacLeod (Founder/Specialist), Sarah Kim (Thermal Engineer), Alex Rodriguez (Project Manager), 20 construction professionals',
            'team_founder_bio': '14 years cold-climate construction experience, building science specialist, extreme weather construction expert',
            'research_linkedin_query': '"cold climate construction" Edmonton "building science" extreme weather',
            'research_verification_sources': 'LinkedIn profile, Edmonton Journal, Cold Climate Housing Research Center',
            'research_work_history': 'Project Manager at PCL Construction, Cold Climate Specialist at ATCO',
            'research_education_summary': 'NAIT Construction Engineering Technology, Cold Climate Building Science Certification',
            'media_press_coverage': 'Edmonton Journal Construction Innovation 2022, Canadian Contractor feature',
            'media_awards_recognition': 'Alberta Construction Association Innovation Award 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Cold climate specialist, extreme weather construction expert',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Arctic Build Solutions Inc.',
            'li_current_title': 'Founder & Cold Climate Specialist',
            'li_work_experience': '2021-Present: Founder Arctic Build Solutions | 2016-2021: Project Manager PCL Construction | 2013-2016: Cold Climate Specialist ATCO',
            'li_education_background': 'NAIT Construction Engineering Technology (2011-2013) | Cold Climate Building Science Certification (2015)',
            'li_professional_skills': 'Cold Climate Construction | Building Science | Thermal Engineering | Project Management | Extreme Weather Building | Energy Efficiency',
            'li_recent_activity': 'Extreme cold construction techniques research | New thermal building system | Alberta construction industry leadership',
            'notes_area_of_expertise': 'Cold_Climate_Construction|Building_Science|Thermal_Engineering',
            'notes_community_engagement': 'Cold_Climate_Housing_Research_Center|Alberta_Construction_Association|Canadian_Construction_Association',
            'notes_business_focus': 'Cold_Climate_Construction|Extreme_Weather_Building|Thermal_Systems'
        }
    ]
    
    # Add all US founders
    for founder in us_construction_contracting:
        collector.add_founder(founder)
    
    # Add Canadian founders
    for founder in canadian_construction_contracting:
        collector.add_founder(founder)
    
    print(f"\n✅ Added 16 Construction & Contracting founders (14 US + 2 Canada)")
    print(f"Construction & Contracting sector: COMPLETE (16/16)")

if __name__ == "__main__":
    collect_construction_contracting_founders()
    collector.show_progress()