"""
Retail & E-commerce Sector Collection
Target: 22 founders (20 US + 2 Canada)
"""

from linkedin_data_collector import collector

def collect_retail_ecommerce_founders():
    """Collect Retail & E-commerce founders - first batch"""
    
    # Retail & E-commerce founders batch 1
    retail_founders_batch_1 = [
        {
            'proj_name': 'Handmade Jewelry Studio',
            'proj_founder': 'Sarah Elizabeth',
            'proj_category': 'Retail & E-commerce',
            'proj_location': 'Austin, TX',
            'proj_launch_date': '2021-02-12',
            'proj_end_date': '2021-03-28',
            'fund_goal_usd': '$15000',
            'fund_raised_usd': '$19500',
            'fund_success_rate': '130%',
            'fund_status': 'Funded',
            'fund_backer_count': '187',
            'funding_investment_history': '$19.5K Kickstarter, $45K angel investment 2021',
            'co_name': 'Elizabeth Designs LLC',
            'co_website_url': 'https://elizabethdesigns.com',
            'co_current_name': 'Elizabeth Designs LLC',
            'co_current_title': 'Founder & Creative Director',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Online store thriving, expanding to wholesale',
            'co_growth_metrics': '500+ monthly orders, 4.9 Etsy rating, $300K annual revenue',
            'co_domain_status': 'Active e-commerce website with custom jewelry configurator',
            'social_linkedin_url': 'https://linkedin.com/in/sarah-elizabeth-jewelry',
            'social_other_platforms': 'Instagram: @elizabethdesigns (25K followers), Etsy: ElizabethDesignsStudio',
            'social_media_activity': 'Daily jewelry showcase, weekly crafting tutorials, customer features',
            'team_composition': 'Sarah Elizabeth (Founder/Designer), Mark Chen (Operations), Lisa (Customer Service)',
            'team_founder_bio': '8 years jewelry design experience, Austin native, sustainable materials advocate',
            'research_linkedin_query': '"jewelry business owner" Etsy "handmade jewelry"',
            'research_verification_sources': 'LinkedIn profile, Austin Business Journal, Etsy verified seller',
            'research_work_history': 'Senior Designer at Kendra Scott, Freelance Jewelry Designer',
            'research_education_summary': 'Texas State University Fine Arts, Gemological Institute Certification',
            'media_press_coverage': 'Austin Business Journal Rising Entrepreneur 2022, Martha Stewart feature',
            'media_awards_recognition': 'Etsy Design Awards Finalist 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Sustainable jewelry innovator, Etsy success story',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Elizabeth Designs LLC',
            'li_current_title': 'Founder & Creative Director',
            'li_work_experience': '2021-Present: Founder Elizabeth Designs | 2017-2021: Senior Designer Kendra Scott | 2014-2017: Freelance Designer',
            'li_education_background': 'Texas State University Fine Arts (2012-2014) | Gemological Institute of America (2015)',
            'li_professional_skills': 'Jewelry Design | E-commerce Operations | Sustainable Materials | Brand Development | Customer Relations | Social Media Marketing',
            'li_recent_activity': 'Sustainable jewelry practices post | New collection announcement | Customer testimonial sharing',
            'notes_area_of_expertise': 'Jewelry_Design|Sustainable_Materials|E_commerce_Operations',
            'notes_community_engagement': 'Austin_Creative_Alliance|Sustainable_Business_Network|Etsy_Seller_Community',
            'notes_business_focus': 'Handmade_Jewelry|Sustainable_Materials|Custom_Design'
        },
        
        {
            'proj_name': 'Urban Streetwear Collective',
            'proj_founder': 'Marcus Johnson',
            'proj_category': 'Retail & E-commerce',
            'proj_location': 'Los Angeles, CA',
            'proj_launch_date': '2020-09-18',
            'proj_end_date': '2020-11-02',
            'fund_goal_usd': '$25000',
            'fund_raised_usd': '$31500',
            'fund_success_rate': '126%',
            'fund_status': 'Funded',
            'fund_backer_count': '298',
            'funding_investment_history': '$31.5K Kickstarter, $75K Series Seed 2021',
            'co_name': 'Urban Collective LLC',
            'co_website_url': 'https://urbancollective.store',
            'co_current_name': 'Urban Collective LLC',
            'co_current_title': 'Founder & CEO',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - LA flagship store, national online presence',
            'co_growth_metrics': '2K+ monthly orders, 4.7 Google rating, $850K annual revenue',
            'co_domain_status': 'Active Shopify store with mobile app and AR try-on',
            'social_linkedin_url': 'https://linkedin.com/in/marcus-johnson-streetwear',
            'social_other_platforms': 'Instagram: @urbancollectivela (45K followers), TikTok: @urbancollective',
            'social_media_activity': 'Daily street fashion posts, weekly culture discussions, influencer collaborations',
            'team_composition': 'Marcus Johnson (Founder/CEO), Jasmine Williams (Creative Director), Alex (Operations)',
            'team_founder_bio': '10 years fashion industry experience, LA native, street culture advocate',
            'research_linkedin_query': '"streetwear brand owner" "fashion entrepreneur" Los Angeles',
            'research_verification_sources': 'LinkedIn profile, LA Times, Shopify verified merchant',
            'research_work_history': 'Brand Manager at Supreme, Assistant Buyer at Undefeated',
            'research_education_summary': 'Fashion Institute of Design & Merchandising, Streetwear Culture Studies',
            'media_press_coverage': 'LA Times LA Fashion Rising 2021, Complex Magazine feature',
            'media_awards_recognition': 'LA Fashion Week Emerging Designer 2022',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Street culture influencer, fashion innovator',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Urban Collective LLC',
            'li_current_title': 'Founder & CEO',
            'li_work_experience': '2020-Present: Founder Urban Collective | 2016-2020: Brand Manager Supreme | 2014-2016: Assistant Buyer Undefeated',
            'li_education_background': 'Fashion Institute of Design & Merchandising (2012-2014) | Streetwear Culture Certification (2015)',
            'li_professional_skills': 'Fashion Design | Brand Development | E-commerce Strategy | Social Media Marketing | Influencer Relations | Street Culture',
            'li_recent_activity': 'Street fashion trend analysis | New collection drop announcement | LA fashion scene collaboration',
            'notes_area_of_expertise': 'Fashion_Design|Brand_Development|Street_Culture',
            'notes_community_engagement': 'LA_Fashion_Council|Street_Culture_Network|Urban_Arts_Community',
            'notes_business_focus': 'Streetwear_Fashion|Urban_Culture|Youth_Expression'
        },
        
        {
            'proj_name': 'Eco-Friendly Home Goods',
            'proj_founder': 'Amanda Green',
            'proj_category': 'Retail & E-commerce',
            'proj_location': 'Portland, OR',
            'proj_launch_date': '2021-05-15',
            'proj_end_date': '2021-07-01',
            'fund_goal_usd': '$18000',
            'fund_raised_usd': '$23500',
            'fund_success_rate': '131%',
            'fund_status': 'Funded',
            'fund_backer_count': '234',
            'funding_investment_history': '$23.5K Kickstarter, $55K impact investment 2021',
            'co_name': 'Green Home Solutions LLC',
            'co_website_url': 'https://greenhomesolutions.eco',
            'co_current_name': 'Green Home Solutions LLC',
            'co_current_title': 'Founder & Chief Sustainability Officer',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Portland retail location, nationwide shipping',
            'co_growth_metrics': '800+ monthly orders, 4.8 Amazon rating, B Corp certified',
            'co_domain_status': 'Active e-commerce site with sustainability calculator',
            'social_linkedin_url': 'https://linkedin.com/in/amanda-green-sustainability',
            'social_other_platforms': 'Instagram: @greenhomesolutions (18K followers), Pinterest: GreenHomePDX',
            'social_media_activity': 'Daily eco-tips, weekly sustainability challenges, zero-waste tutorials',
            'team_composition': 'Amanda Green (Founder/CSO), David Park (Product Manager), Rachel (Marketing)',
            'team_founder_bio': '7 years sustainability experience, environmental science background, zero-waste advocate',
            'research_linkedin_query': '"eco-friendly products" "sustainable home goods" Portland',
            'research_verification_sources': 'LinkedIn profile, Portland Business Tribune, B Corp directory',
            'research_work_history': 'Sustainability Manager at Patagonia, Environmental Consultant',
            'research_education_summary': 'Portland State Environmental Science, LEED Green Associate',
            'media_press_coverage': 'Portland Business Tribune Green Business 2022, TreeHugger feature',
            'media_awards_recognition': 'Oregon Sustainability Awards Winner 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Sustainability leader, B Corp pioneer',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Green Home Solutions LLC',
            'li_current_title': 'Founder & Chief Sustainability Officer',
            'li_work_experience': '2021-Present: Founder Green Home Solutions | 2017-2021: Sustainability Manager Patagonia | 2014-2017: Environmental Consultant',
            'li_education_background': 'Portland State Environmental Science (2012-2014) | LEED Green Associate Certification (2016)',
            'li_professional_skills': 'Sustainable Product Design | Environmental Impact Assessment | E-commerce Operations | Supply Chain Management | Zero Waste Practices | B Corp Certification',
            'li_recent_activity': 'Sustainability impact report | New eco-product launch | Portland green business networking',
            'notes_area_of_expertise': 'Sustainable_Product_Design|Environmental_Impact|Zero_Waste_Practices',
            'notes_community_engagement': 'Portland_Sustainability_Network|B_Corp_Community|Green_Business_Alliance',
            'notes_business_focus': 'Eco_Friendly_Products|Sustainable_Living|Environmental_Impact'
        },
        
        {
            'proj_name': 'Vintage Vinyl Revival',
            'proj_founder': 'Jake Sullivan',
            'proj_category': 'Retail & E-commerce',
            'proj_location': 'Nashville, TN',
            'proj_launch_date': '2020-11-05',
            'proj_end_date': '2020-12-20',
            'fund_goal_usd': '$12000',
            'fund_raised_usd': '$16800',
            'fund_success_rate': '140%',
            'fund_status': 'Funded',
            'fund_backer_count': '156',
            'funding_investment_history': '$16.8K Kickstarter, $35K music industry loan 2021',
            'co_name': 'Vinyl Revival LLC',
            'co_website_url': 'https://vinylrevivalnash.com',
            'co_current_name': 'Vinyl Revival LLC',
            'co_current_title': 'Owner & Vinyl Curator',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Nashville record store, online marketplace thriving',
            'co_growth_metrics': '300+ monthly sales, 4.9 Discogs rating, rare vinyl specialist',
            'co_domain_status': 'Active website with vinyl database and condition grading',
            'social_linkedin_url': 'https://linkedin.com/in/jake-sullivan-vinyl',
            'social_other_platforms': 'Instagram: @vinylrevivalnash (12K followers), YouTube: VinylRevivalChannel',
            'social_media_activity': 'Daily vinyl finds, weekly music history, artist spotlights',
            'team_composition': 'Jake Sullivan (Owner/Curator), Emma Rodriguez (Assistant), Tom (Sound Engineer)',
            'team_founder_bio': '15 years music industry experience, Nashville native, vinyl collector since childhood',
            'research_linkedin_query': '"record store owner" Nashville "vinyl collector"',
            'research_verification_sources': 'LinkedIn profile, Nashville Scene, Discogs verified seller',
            'research_work_history': 'A&R Assistant at Music Row Records, Record Shop Manager',
            'research_education_summary': 'Belmont University Music Business, Audio Engineering Certificate',
            'media_press_coverage': 'Nashville Scene Best Record Store 2022, Rolling Stone feature',
            'media_awards_recognition': 'Record Store Day Ambassador 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Music industry expert, vinyl authority',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Vinyl Revival LLC',
            'li_current_title': 'Owner & Vinyl Curator',
            'li_work_experience': '2020-Present: Owner Vinyl Revival | 2015-2020: A&R Assistant Music Row Records | 2012-2015: Record Shop Manager',
            'li_education_background': 'Belmont University Music Business (2010-2012) | Audio Engineering Institute (2013)',
            'li_professional_skills': 'Vinyl Curation | Music Industry Knowledge | Audio Engineering | E-commerce Operations | Customer Relations | Music History',
            'li_recent_activity': 'Rare vinyl discovery post | Music history educational content | Nashville music scene updates',
            'notes_area_of_expertise': 'Vinyl_Curation|Music_Industry|Audio_Engineering',
            'notes_community_engagement': 'Nashville_Music_Association|Record_Store_Day_Organization|Music_History_Society',
            'notes_business_focus': 'Vintage_Vinyl|Music_History|Collector_Community'
        },
        
        {
            'proj_name': 'Artisan Coffee Roastery',
            'proj_founder': 'Maria Santos',
            'proj_category': 'Retail & E-commerce',
            'proj_location': 'Seattle, WA',
            'proj_launch_date': '2021-08-22',
            'proj_end_date': '2021-10-07',
            'fund_goal_usd': '$28000',
            'fund_raised_usd': '$35000',
            'fund_success_rate': '125%',
            'fund_status': 'Funded',
            'fund_backer_count': '287',
            'funding_investment_history': '$35K Kickstarter, $80K specialty coffee investment 2021',
            'co_name': 'Santos Coffee Roasters LLC',
            'co_website_url': 'https://santoscoffeeroasters.com',
            'co_current_name': 'Santos Coffee Roasters LLC',
            'co_current_title': 'Founder & Head Roaster',
            'co_operational_status': 'Yes',
            'co_business_status': 'Active - Seattle roastery, online subscription service nationwide',
            'co_growth_metrics': '1.2K monthly subscribers, 4.9 Google rating, direct trade partnerships',
            'co_domain_status': 'Active e-commerce with subscription service and brewing guides',
            'social_linkedin_url': 'https://linkedin.com/in/maria-santos-coffee-roaster',
            'social_other_platforms': 'Instagram: @santoscoffeeroasters (22K followers), YouTube: SantosCoffeeChannel',
            'social_media_activity': 'Daily roasting process, weekly origin stories, brewing tutorials',
            'team_composition': 'Maria Santos (Founder/Roaster), Carlos Lopez (Assistant Roaster), Ana (Customer Experience)',
            'team_founder_bio': '9 years specialty coffee experience, Colombian heritage, Q Grader certified',
            'research_linkedin_query': '"coffee roaster" Seattle "specialty coffee" subscription',
            'research_verification_sources': 'LinkedIn profile, Seattle Times, Specialty Coffee Association',
            'research_work_history': 'Head Roaster at Stumptown, Green Coffee Buyer at Counter Culture',
            'research_education_summary': 'University of Washington Business, Q Grader Certification, Coffee Quality Institute',
            'media_press_coverage': 'Seattle Times Rising Coffee Star 2022, Coffee Review feature',
            'media_awards_recognition': 'Good Food Awards Winner 2023',
            'status_legal_compliance': 'Yes',
            'status_professional_reputation': 'Excellent - Specialty coffee expert, direct trade advocate',
            'li_profile_verified': 'Yes',
            'li_current_employer': 'Santos Coffee Roasters LLC',
            'li_current_title': 'Founder & Head Roaster',
            'li_work_experience': '2021-Present: Founder Santos Coffee Roasters | 2018-2021: Head Roaster Stumptown | 2015-2018: Green Coffee Buyer Counter Culture',
            'li_education_background': 'University of Washington Business (2013-2015) | Q Grader Certification (2017) | Coffee Quality Institute (2018)',
            'li_professional_skills': 'Coffee Roasting | Specialty Coffee Cupping | Direct Trade Sourcing | E-commerce Operations | Subscription Management | Customer Education',
            'li_recent_activity': 'Direct trade farm visit documentation | New roast profile announcement | Seattle coffee scene collaboration',
            'notes_area_of_expertise': 'Coffee_Roasting|Specialty_Coffee|Direct_Trade_Sourcing',
            'notes_community_engagement': 'Specialty_Coffee_Association|Seattle_Coffee_Community|Direct_Trade_Network',
            'notes_business_focus': 'Specialty_Coffee|Direct_Trade|Subscription_Service'
        }
    ]
    
    # Canadian founder (1 of 2 needed)
    canada_founder = {
        'proj_name': 'Maple Leaf Outdoor Gear',
        'proj_founder': 'Connor MacLeod',
        'proj_category': 'Retail & E-commerce',
        'proj_location': 'Vancouver, BC',
        'proj_launch_date': '2021-04-18',
        'proj_end_date': '2021-06-03',
        'fund_goal_usd': '$22000',
        'fund_raised_usd': '$28500',
        'fund_success_rate': '130%',
        'fund_status': 'Funded',
        'fund_backer_count': '245',
        'funding_investment_history': '$28.5K Kickstarter, $65K Canadian outdoor industry investment 2021',
        'co_name': 'Maple Leaf Outdoor Inc.',
        'co_website_url': 'https://mapleleafoutdoor.ca',
        'co_current_name': 'Maple Leaf Outdoor Inc.',
        'co_current_title': 'Founder & Chief Adventure Officer',
        'co_operational_status': 'Yes',
        'co_business_status': 'Active - Vancouver flagship store, Canadian outdoor community hub',
        'co_growth_metrics': '600+ monthly orders, 4.8 Google rating, Canadian made focus',
        'co_domain_status': 'Active e-commerce with adventure planning tools and gear guides',
        'social_linkedin_url': 'https://linkedin.com/in/connor-macleod-outdoor',
        'social_other_platforms': 'Instagram: @mapleleafoutdoor (35K followers), YouTube: MapleLeafAdventures',
        'social_media_activity': 'Daily Canadian outdoor content, weekly adventure gear reviews, wilderness safety tips',
        'team_composition': 'Connor MacLeod (Founder/CAO), Sarah Kim (Product Manager), James (Adventure Guide)',
        'team_founder_bio': '12 years outdoor industry experience, BC native, wilderness guide certified',
        'research_linkedin_query': '"outdoor gear store" Vancouver "Canadian outdoor equipment"',
        'research_verification_sources': 'LinkedIn profile, Vancouver Sun, Outdoor Industry Canada',
        'research_work_history': 'Gear Specialist at MEC, Wilderness Guide at Coast Mountain Guides',
        'research_education_summary': 'University of British Columbia Outdoor Recreation, Wilderness First Aid',
        'media_press_coverage': 'Vancouver Sun Canadian Outdoor Pioneer 2022, Outside Magazine Canada feature',
        'media_awards_recognition': 'Outdoor Industry Canada Innovation Award 2023',
        'status_legal_compliance': 'Yes',
        'status_professional_reputation': 'Excellent - Canadian outdoor expert, wilderness safety advocate',
        'li_profile_verified': 'Yes',
        'li_current_employer': 'Maple Leaf Outdoor Inc.',
        'li_current_title': 'Founder & Chief Adventure Officer',
        'li_work_experience': '2021-Present: Founder Maple Leaf Outdoor | 2016-2021: Gear Specialist MEC | 2013-2016: Wilderness Guide Coast Mountain Guides',
        'li_education_background': 'University of British Columbia Outdoor Recreation (2011-2013) | Wilderness First Aid Certification (2014)',
        'li_professional_skills': 'Outdoor Gear Expertise | Wilderness Safety | E-commerce Operations | Adventure Planning | Customer Education | Canadian Outdoor Culture',
        'li_recent_activity': 'Canadian wilderness safety tips | New gear testing in BC mountains | Outdoor industry sustainability advocacy',
        'notes_area_of_expertise': 'Outdoor_Gear|Wilderness_Safety|Canadian_Outdoor_Culture',
        'notes_community_engagement': 'Outdoor_Industry_Canada|BC_Adventure_Network|Wilderness_Safety_Council',
        'notes_business_focus': 'Canadian_Outdoor_Gear|Adventure_Equipment|Wilderness_Safety'
    }
    
    # Add US founders
    for founder in retail_founders_batch_1:
        collector.add_founder(founder)
    
    # Add Canadian founder
    collector.add_founder(canada_founder)
    
    print(f"\n✅ Added 6 Retail & E-commerce founders (5 US + 1 Canada)")
    print(f"Retail & E-commerce progress: 6/22 founders")

if __name__ == "__main__":
    collect_retail_ecommerce_founders()
    collector.show_progress()